name: Deploy

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v2
        with: 
          node-version: 16
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: schoolar_app
          mysql user: schoolar_app
          mysql password: password
      - name: Copy .env
        run: cp .env.example .env
      - name: Install composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup Project
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
          php artisan jwt:secret
      - name: Directory Permissions
        run: chmod 755 -R storage bootstrap/cache
      - name: Run Unit tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_USERNAME: laravel_test_user
          DB_PASSWORD: super_secret
          DB_DATABASE: laravel_test_db
        run: php artisan test
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd /home/cfciruxn
            cd schoolar_app
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            git pull origin main
            php artisan jwt:secret
#            git clone https://oauth2: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@github.com/eldast8sman/schoolar-app.git schoolar_app